# Default values for pgbouncer.
# This is a YAML-formatted file.

replicaCount: 1

imagePullSecrets: []
 # - name: "image-pull-secret"

## pgbouncer container image
##
image:
  repository: kvelichkowallarm/pgbouncer
  tag: 1.0.0
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

## pgbouncer service configuration
##
service:
  type: ClusterIP
  port: 5432

## Resource requests and limits
## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources: {}
 # limits:
 #   cpu: 10m
 #   memory: 32Mi
 # requests:
 #   cpu: 10m
 #   memory: 32Mi

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
#
nodeSelector: {}

## Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## Affinity for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## pgbouncer configuration
##
config:
  adminUser: admin
  adminPassword:
  authUser:
  authPassword:
  databases: {}
   # <DB_NAME>:
   #  host: <DB_HOST>
   #  port: <DB_PORT>
  pgbouncer: 
    auth_type: md5
    pool_mode: transaction
    max_client_conn: 1024
    default_pool_size: 20
  userlist: {}
   # <USERNAME>: <PASSWORD> 


## pgbouncer config reload container image and configuration
##
pgbouncerConfigReload:
  name: control
  reloadTimeout: 10
  logJson: 1
  image:
    repository: kvelichkowallarm/pgbouncer-config-reload
    tag: 1.0.1
    pullPolicy: Always

## pgbouncer exporter container image and configuration
##
pgbouncerExporter:
  name: exporter
  port: 9127
  image:
    repository: spreaker/prometheus-pgbouncer-exporter
    tag: 2.0.1
    pullPolicy: IfNotPresent
